---
- name: Install Docker
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker's official GPG key
  become: yes
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Set up the Docker stable repository
  become: yes
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update apt package index
  become: yes
  apt:
    update_cache: yes

- name: Install Docker CE
  become: yes
  apt:
    name: docker-ce
    state: present

- name: Start and enable Docker
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
